server:
  port: 8090

spring:
  jpa:
    show-sql: true
    generate-ddl: false
    database: MYSQL
  datasource:
    platform: postgres
    url: jdbc:mysql://localhost:3307/atm
    username: myuser
    password: mypass
    driverClassName: com.mysql.jdbc.Driver

liquibase:
  change-log: "classpath:db/master.xml"

atm:
  security:
    cors:
      enabled: true
    oauth2:
      jwt:
        signing-key: "jwt-secret-key-123"

security:
  oauth2:
    resource:
      # Seems that in order to have 'OAuth2AuthenticationProcessingFilter' filter for decoding OAuth2 tokens working
      # had to set the filter order to 1 instead of 0.
      # 0 being used by the Authorization Server.
      # Open issue at: https://github.com/spring-projects/spring-security-oauth/issues/1016.
      filter-order: 1
